name: Build MinGW toolchains

on:
  push:
    branches:
      - 'trunk'
  workflow_dispatch:

jobs:
  prepare:
    name: Compute release tag
    runs-on: ubuntu-latest
    outputs:
      tag_date: ${{ steps.set.outputs.tag_date }}
    steps:
      - name: Compute timestamp
        id: set
        run: echo "tag_date=$(date -u +'%Y%m%dT%H%M%SZ')" >> "$GITHUB_OUTPUT"

  build:
    needs: prepare
    strategy:
      matrix:
        target_arch: [i486, i586, i686]

    name: Build MinGW toolchain for ${{matrix.target_arch}}
    runs-on: ubuntu-latest
    container: archlinux:latest

    steps:
      - name: Install dependencies
        run: pacman --noconfirm -Syu && pacman --needed --noconfirm -S base-devel git autoconf automake wget bison flex texinfo file

      - name: Checkout code
        uses: actions/checkout@v7

      - name: Git config
        run: git config --global --add safe.directory "$GITHUB_WORKSPACE"

      - name: Build toolchain for ${{matrix.target_arch}}
        run: TARGET=${{matrix.target_arch}}-w64-mingw32 ./make_toolchain.sh

      - name: Pack toolchain into tarball
        run: |
          mv toolchain/output mingw-${{matrix.target_arch}}
          tar -Jcvf mingw-${{matrix.target_arch}}.tar.xz mingw-${{matrix.target_arch}}

      - name: Upload MinGW artifact
        uses: actions/upload-artifact@v7
        with:
          name: mingw-${{ matrix.target_arch }}
          path: mingw-*.tar.xz
          if-no-files-found: error

  release:
    needs: [prepare, build]
    name: Publish release
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v7

      - name: Download all libgcc artifacts
        uses: actions/download-artifact@v8
        with:
          path: artifacts
          pattern: mingw-*
          merge-multiple: true

      - name: Read toolchain versions
        run: |
          grep -o 'GCCVERSION=.*$' make_toolchain.sh >> $GITHUB_ENV
          grep -o 'BINUTILSVERSION=.*$' make_toolchain.sh >> $GITHUB_ENV
          grep -o 'MINGWVERSION=.*$' make_toolchain.sh >> $GITHUB_ENV

      - name: Tag new release
        run: |
          git tag ${{ needs.prepare.outputs.tag_date }}
          git push --tags

      - name: Create new release
        uses: softprops/action-gh-release@v3
        with:
          name: MinGW binary build ${{ needs.prepare.outputs.tag_date }}
          tag_name: ${{ needs.prepare.outputs.tag_date }}
          body: |
            MinGW cross-compiler toolchains for Linux targetting 32-bit Windows.

            This build is based on:
              - GNU Binutils ${{ env.BINUTILSVERSION }}
              - GCC ${{ env.GCCVERSION }}
              - MinGW ${{ env.MINGWVERSION }}
          files: |
            artifacts/mingw-*.tar.xz
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
